export const LOG_PLUGIN_NAME = '[svg-spritesheet]'
export const DEFAULT_BATCH_SIZE = 20
export const GENERATED_FILE_HEADER = `
/**
 * WARN: Do not edit this file. It was generated from \`vite.config.ts\`.
 */
`.trim()
