name: CI

run-name: 'CI - ${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test plugin

    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4

      - name: 'Install'
        run: npm ci

      - name: 'Formatting'
        run: npm run format:check

      - name: 'Lint'
        run: npm run lint

      - name: 'Typecheck'
        run: npm run typecheck

      - name: 'Test and coverage'
        run: npm run coverage
