name: CI

run-name: 'CI - ${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-matrix:
    name: CI

    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Run tests with coverage
        run: pnpm run coverage
